#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'pyzim-trunk',
 'build_date': '2013-04-30 19:36:50 +0200',
 'clean': None,
 'date': '2013-04-30 19:27:20 +0200',
 'revision_id': 'jaap.karssenberg@gmail.com-20130430172720-n6jaw95wiyevdqln',
 'revno': '672'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)s' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
